-- Semilla de servicios (site_services) — 9 servicios de PIYC.
-- GENERADO desde src/data/servicios.ts: los dos archivos son el mismo contenido.
-- Si cambia uno, se regenera el otro (no se editan a mano por separado).
--
-- Origen de los nombres: docs/PLAN_INICIAL_PIYC.md §4.4 (documento del Drive de
-- PIYC). Los párrafos de `description` y las listas de `items` los redactó el
-- equipo de la web y están PENDIENTES DE APROBACIÓN de Jorge.
--
-- Sin cifras, clientes, certificaciones ni marcas representadas: nada de eso
-- está confirmado. Las normas y protocolos citados son estándares del sector.
--
-- Las fotos son las del Drive de PIYC (carpeta «9. FOTOS»), catalogadas en
-- docs/CONTENIDO.md §2. Cada servicio lleva fotos propias: ninguna se repite en
-- otra sección del sitio. Las capturas de HMI, SCADA y planos quedaron
-- reservadas para los casos de éxito, que son de donde salieron.
--
-- `aires-acondicionados` va con images = '{}': el Drive no trae ni una foto de
-- ese servicio (docs/CONTENIDO.md §2.3). `refrigeracion-industrial` va con una
-- sola, la del montaje en la sala con paneles aislantes.
--
-- `cover` = primera foto de `gallery`, siempre apaisada: es el fondo de la
-- cabecera de la ficha. Lleva `srcMovil` (variante de 900 px) y medidas reales.
--
-- Idempotente: se puede volver a correr. `on conflict (slug) do update` deja la
-- fila como dice este archivo, salvo `published`, que respeta lo que haya
-- decidido el panel.

insert into public.site_services
  (slug, title, nav_title, icon_key, summary, description, items, images, video,
   meta_title, meta_description, sort, published)
values
  ('automatizacion-procesos-industriales', 'Automatización de procesos industriales', 'Automatización y control', 'automatizacion',
   'Control con PLC y supervisión HMI/SCADA para que el proceso trabaje por receta, repita el resultado y deje registro de lo que pasó.',
   'Automatizar un proceso es convertir una secuencia que hoy depende del criterio del operario en una lógica que se ejecuta igual todas las veces. Levantamos la secuencia real en planta —qué arranca con qué, qué enclavamientos existen, qué se mide y qué se decide con esa medida—, la escribimos en el PLC y la ponemos a la vista del operario en una HMI que muestra el estado del proceso, no una lista de señales.

Programamos el control en los lenguajes de la norma IEC 61131-3 (escalera, bloques funcionales y texto estructurado según lo que convenga a cada rutina) y lo estructuramos para que otro ingeniero lo pueda leer: rutinas separadas por área, señales con nombre y comentarios en español. Sobre esa base montamos el manejo por formulación o receta, los lazos de control PID, las secuencias de limpieza, los permisivos de seguridad y el registro de alarmas con su marca de tiempo.

La supervisión HMI/SCADA cierra el trabajo: pantallas de operación, tendencias de las variables que importan, históricos y reportes de producción. Integramos los equipos de campo por los protocolos que ya existen en la planta —Modbus RTU y TCP, Profibus, Profinet, EtherNet/IP— para no obligar a cambiar lo que funciona, y dejamos el respaldo de programas y la documentación en manos del cliente.',
   '["Levantamiento de la secuencia de proceso y definición de la lista de señales (I/O)","Programación de PLC bajo IEC 61131-3: escalera, bloques funcionales y texto estructurado","Manejo por formulación o receta, lazos PID, enclavamientos y permisivos de seguridad","Desarrollo de pantallas HMI de operación con tendencias, alarmas y eventos fechados","Sistemas SCADA con históricos, reportes de producción y conexión a bases de datos","Integración de equipos por Modbus RTU/TCP, Profibus, Profinet y EtherNet/IP","Migración y actualización de PLC obsoletos conservando la lógica del proceso","Puesta en marcha en sitio, pruebas con el operario y entrega de programas documentados"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/automatizacion-procesos-industriales/tablero-inox-plc-compacto-apaisada.webp","coverAlt":"Tablero en acero inoxidable con PLC compacto, switch de red, protecciones y borneras cableadas","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/automatizacion-procesos-industriales/tablero-inox-plc-compacto-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/automatizacion-procesos-industriales/tablero-inox-plc-compacto-apaisada-900.webp","alt":"Tablero en acero inoxidable con PLC compacto, switch de red, protecciones y borneras cableadas","width":1836,"height":1033},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/automatizacion-procesos-industriales/tablero-inox-plc-borneras.webp","alt":"Tablero de automatización en acero inoxidable con PLC compacto, fuente de 24 V y borneras identificadas una a una","width":888,"height":1920},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/automatizacion-procesos-industriales/tablero-plc-compacto-red.webp","alt":"Tablero con PLC compacto, switch de red industrial y fuente conmutada, cableado y marquillado","width":889,"height":1920}]}'::jsonb, null,
   'Automatización de procesos industriales',
   'Control con PLC y supervisión HMI/SCADA para procesos industriales en Cali: lógica por receta, lazos PID, alarmas fechadas e integración con la planta.',
   10, true),
  ('diseno-ingenieria-electrica', 'Diseño y desarrollo de proyectos de ingeniería eléctrica', 'Ingeniería eléctrica', 'plano',
   'Del levantamiento en sitio al plano as-built: unifilares, cuadros de carga, P&ID y memorias que sostienen el montaje y el mantenimiento.',
   'Un montaje eléctrico sin planos se paga dos veces: primero en la obra, adivinando qué llega a cada borne, y después en cada mantenimiento. Por eso el diseño arranca en la planta: levantamos lo que hay instalado, medimos las cargas reales, revisamos el estado de las canalizaciones y solo entonces dibujamos.

Entregamos el juego completo de documentos con el que se construye y se opera la instalación: diagrama unifilar, cuadro de cargas, cálculo de conductores y de las protecciones que los acompañan, planos de fuerza, de control y de mando, diagramas de conexionado y listas de borneras. Cuando el proyecto tiene proceso, el paquete incluye el P&ID con la instrumentación y la lista de señales, que es la misma que después alimenta la programación del PLC.

El diseño también decide equipos: arrancadores directos o suaves, variadores de velocidad, transformadores, transferencias y esquemas de puesta a tierra, dimensionados según la carga y no según el catálogo que estaba a mano. Al cierre se actualizan los planos con lo que quedó realmente instalado —el as-built— y se entregan las memorias de cálculo, que son el documento al que se vuelve cuando la planta crece.',
   '["Levantamiento en sitio y revisión del estado de la instalación existente","Diagrama unifilar, cuadro de cargas y balance de fases","Cálculo de conductores, canalizaciones y coordinación de protecciones","Planos de fuerza, control y mando; diagramas de conexionado y listas de borneras","P&ID del proceso, hoja de instrumentos y lista de señales (I/O)","Selección y dimensionamiento de arrancadores, variadores, transformadores y transferencias","Memorias de cálculo y actualización de planos as-built al cierre del proyecto"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/diseno-ingenieria-electrica/tablero-potencia-interruptores-apaisada.webp","coverAlt":"Interior de un tablero de potencia con el seccionador de entrada y cuatro interruptores de caja moldeada","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/diseno-ingenieria-electrica/tablero-potencia-interruptores-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/diseno-ingenieria-electrica/tablero-potencia-interruptores-apaisada-900.webp","alt":"Interior de un tablero de potencia con el seccionador de entrada y cuatro interruptores de caja moldeada","width":1920,"height":1080},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/diseno-ingenieria-electrica/tableros-cuarto-electrico.webp","alt":"Dos tableros cerrados instalados en un cuarto eléctrico, con ventilación forzada y panel de medición en la puerta","width":934,"height":1920}]}'::jsonb, null,
   'Ingeniería eléctrica y diseño de proyectos',
   'Diseño eléctrico en Cali: unifilares, cuadros de carga, cálculo de conductores y protecciones, P&ID, planos de control y memorias as-built.',
   20, true),
  ('tableros-de-control', 'Ensamble de tableros de control y potencia', 'Tableros de control', 'tablero',
   'Tableros armados según plano, con cableado identificado y disipación calculada. Se abren dentro de cinco años y se siguen entendiendo.',
   'Un tablero bien armado se reconoce con la puerta abierta: los conductores van por canaleta y no por el aire, cada hilo tiene su marquilla, las borneras están numeradas igual que en el plano y hay espacio para crecer. Armamos tableros de control y de potencia a la medida del proyecto, partiendo siempre del diagrama y del cuadro de cargas, no de un gabinete estándar al que después se le hace caber todo.

El montaje incluye la distribución física dentro del gabinete —separando el circuito de potencia del de control para que el ruido eléctrico no se le meta a las señales análogas—, el cálculo de la disipación de calor y la ventilación o climatización que requiera, y el aterrizaje de pantallas y blindajes. Integramos protecciones, contactores, arrancadores suaves, variadores de velocidad, fuentes, PLC, módulos de entradas y salidas y la instrumentación que el proceso necesite.

Antes de que el tablero salga del taller se prueba: continuidad punto a punto contra el plano, verificación de la lógica de mando, pruebas de aislamiento y rotulado final de puertas y componentes. Se entrega con el plano actualizado a lo que quedó dentro, que es lo que hace que el mantenimiento siguiente dure horas y no días.',
   '["Diseño de la distribución interna del gabinete y cálculo de disipación de calor","Tableros de control, de potencia y centros de control de motores (CCM)","Montaje de protecciones, contactores, arrancadores suaves y variadores de velocidad","Integración de PLC, módulos de entradas/salidas, fuentes y relés de interposición","Cableado con marquilla por hilo, borneras numeradas y separación potencia/control","Aterrizaje de pantallas y blindajes de las señales análogas y de comunicación","Pruebas punto a punto contra plano, prueba de aislamiento y rotulado final","Entrega con planos actualizados a lo realmente construido"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/tableros-de-control/tablero-plc-modular-reles-apaisada.webp","coverAlt":"Tablero de gran formato abierto, con PLC modular, bancos de relés de interposición y protecciones","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/tableros-de-control/tablero-doble-puerta-terminado-900.webp","alt":"Tablero de doble puerta terminado, con rejillas de ventilación y visor, listo para despacho","width":900,"height":1200},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/tableros-de-control/tablero-plc-modular-reles-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/tableros-de-control/tablero-plc-modular-reles-apaisada-900.webp","alt":"Tablero de gran formato abierto, con PLC modular, bancos de relés de interposición y protecciones","width":1920,"height":1080}]}'::jsonb, null,
   'Tableros de control y potencia a la medida',
   'Ensamble de tableros de control, potencia y CCM en Cali: armado según plano, cableado marquillado, pruebas punto a punto y planos as-built.',
   30, true),
  ('telemetria', 'Telemetría', 'Telemetría', 'telemetria',
   'Medir lo que pasa en un punto lejano y verlo donde se decide: caudal, nivel, presión, temperatura y consumo, con histórico y alarmas.',
   'La telemetría resuelve un problema concreto: el dato existe en campo pero nadie lo ve a tiempo. Un tanque en otra sede, una estación de bombeo al final de una vía, un medidor en la acometida. Instalamos la instrumentación que toma la medida, el equipo que la transmite y el sistema que la guarda y la muestra.

El trabajo empieza por la medición, porque un dato mal tomado no mejora por viajar rápido: selección e instalación de transmisores de nivel, presión, caudal y temperatura, con su señal de 4–20 mA, su sonda RTD o su salida digital según el caso, y su calibración contra patrón. De ahí la información sube por el medio que el sitio permita —cable, fibra, radio o red celular— usando Modbus, MQTT u otro protocolo abierto, sin quedar amarrada a un fabricante.

En el otro extremo queda un tablero de lectura: valores al instante, tendencias, totalizadores, comparación entre periodos y alarmas por umbral que avisan antes de que el problema se note en la producción. El histórico es lo que convierte la telemetría en una herramienta de gestión y no en un indicador más: con él se ven consumos, fugas, turnos que difieren y equipos que empiezan a degradarse.',
   '["Selección, instalación y calibración de transmisores de nivel, presión, caudal y temperatura","Cableado e integración de señales 4–20 mA, RTD Pt100, pulsos y salidas digitales","Estaciones remotas con PLC o RTU alimentadas por red o por panel solar","Transmisión por radio, red celular o red de planta con protocolos abiertos (Modbus, MQTT)","Almacenamiento histórico, totalizadores y comparación entre periodos","Alarmas por umbral y notificación al responsable del proceso","Tableros de lectura en pantalla de planta, computador o dispositivo móvil"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telemetria/tablero-pared-sala-proceso-apaisada.webp","coverAlt":"Tablero rotulado montado en pared junto al visor de la sala de proceso, con la canalización llevada al equipo","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telemetria/tablero-pared-sala-proceso-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telemetria/tablero-pared-sala-proceso-apaisada-900.webp","alt":"Tablero rotulado montado en pared junto al visor de la sala de proceso, con la canalización llevada al equipo","width":1920,"height":1080}]}'::jsonb, null,
   'Telemetría industrial y medición remota',
   'Telemetría industrial en Cali: instrumentación de campo, estaciones remotas, transmisión por radio o red celular, histórico y alarmas por umbral.',
   40, true),
  ('telecontrol', 'Telecontrol', 'Telecontrol', 'telecontrol',
   'Operar el equipo a distancia con las mismas garantías que en sitio: mando remoto, enclavamientos, permisos por usuario y registro de cada acción.',
   'El telecontrol es el paso siguiente a la telemetría: además de ver, se actúa. Arrancar una bomba, abrir una válvula, cambiar una consigna o pasar un equipo de automático a manual desde el centro de operación o desde un celular, sin que nadie tenga que desplazarse.

Actuar a distancia solo es aceptable si las protecciones viajan con el mando. Por eso los enclavamientos y los permisivos se programan en el PLC de la estación remota, no en la pantalla: si la comunicación se cae, el equipo queda en un estado seguro definido de antemano y no en el último que le ordenaron. Cada comando lleva confirmación, tiempo de espera y verificación de que el equipo respondió; si no respondió, la pantalla lo dice.

El acceso se controla por usuario y por rol: quién puede ver, quién puede operar y quién puede cambiar parámetros, con registro fechado de cada acción y de quién la hizo. Ese registro sirve tanto para auditar como para entender qué ocurrió cuando algo salió distinto. La conexión se levanta sobre la red que el sitio tenga, con el canal cifrado y la estación remota fuera de la internet pública.',
   '["Mando remoto de bombas, válvulas, motores y equipos de proceso","Enclavamientos, permisivos y estado seguro programados en el PLC de la estación remota","Confirmación de comando, tiempo de espera y verificación de respuesta del equipo","Cambio remoto de consignas y paso de automático a manual con trazabilidad","Usuarios y roles: quién ve, quién opera y quién cambia parámetros","Registro fechado de cada acción, con el usuario que la ejecutó","Conexión cifrada sobre red de planta, red celular o VPN; sin exponer el PLC a internet"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telecontrol/tablero-variadores-velocidad-apaisada.webp","coverAlt":"Interior de un tablero con variadores de velocidad de distintas potencias, PLC modular y protecciones","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telecontrol/terminal-operacion-inox.webp","alt":"Terminal de operación en una caja de acero inoxidable montada junto al equipo, con la pantalla del proceso encendida","width":281,"height":498},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telecontrol/tablero-variadores-velocidad-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/telecontrol/tablero-variadores-velocidad-apaisada-900.webp","alt":"Interior de un tablero con variadores de velocidad de distintas potencias, PLC modular y protecciones","width":1920,"height":1080}]}'::jsonb, null,
   'Telecontrol y operación remota de equipos',
   'Telecontrol industrial en Cali: mando remoto de bombas, válvulas y motores con enclavamientos en el PLC, permisos por usuario y registro de cada acción.',
   50, true),
  ('proyectos-llave-en-mano', 'Venta e instalación de proyectos llave en mano', 'Proyectos llave en mano', 'llave-en-mano',
   'Un solo responsable del proyecto completo: ingeniería, suministro, montaje, puesta en marcha y entrega documentada.',
   'Cuando el diseño lo hace uno, el tablero lo arma otro y el montaje lo ejecuta un tercero, los problemas aparecen en las uniones y nadie los reconoce como propios. En un proyecto llave en mano PIYC asume el alcance completo y responde por el resultado: que el sistema quede funcionando y produciendo.

El trabajo cubre la ingeniería de detalle, el suministro de tableros, instrumentación, equipos de control y materiales eléctricos, el montaje electromecánico en planta, la programación del control y la supervisión, y la puesta en marcha con el proceso corriendo. Cada etapa se planea contra las paradas de producción disponibles, porque en una planta en operación la ventana de montaje es parte del diseño, no un detalle logístico.

La entrega no es el arranque: es el arranque más la documentación. Planos as-built, programas del PLC y de la HMI en poder del cliente, manual de operación, capacitación al personal que va a usar el sistema y un periodo de acompañamiento para afinar lo que solo se ve cuando la planta lleva semanas produciendo.',
   '["Ingeniería de detalle y definición del alcance con el equipo de planta","Suministro de tableros, instrumentación, equipos de control y material eléctrico","Montaje electromecánico: canalizaciones, cableado, instrumentos y equipos","Programación del PLC y desarrollo de la supervisión HMI/SCADA","Planeación del montaje contra las ventanas de parada de producción","Puesta en marcha con el proceso en operación y ajuste de lazos de control","Capacitación al personal y entrega de planos, programas y manual de operación","Acompañamiento posterior al arranque para afinar el sistema en producción"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/proyectos-llave-en-mano/linea-empaque-planta.webp","coverAlt":"Línea de transporte y empaque montada dentro de una planta, con el área aislada durante la obra","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/proyectos-llave-en-mano/linea-empaque-planta.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/proyectos-llave-en-mano/linea-empaque-planta-900.webp","alt":"Línea de transporte y empaque montada dentro de una planta, con el área aislada durante la obra","width":1920,"height":934}]}'::jsonb, null,
   'Proyectos industriales llave en mano',
   'Proyectos llave en mano en Cali: ingeniería, suministro, montaje electromecánico, programación, puesta en marcha y entrega documentada.',
   60, true),
  ('aplicaciones-industriales', 'Aplicaciones industriales', 'Aplicaciones industriales', 'aplicaciones',
   'Desarrollos a la medida para lo que ningún equipo de catálogo resuelve: dosificación, pesaje, trazabilidad, bancos de prueba y máquinas especiales.',
   'Hay necesidades de planta que no tienen un equipo comercial que las cubra: una dosificación con una tolerancia que el proveedor no garantiza, un banco de pruebas para un producto propio, una máquina que hay que adaptar a un empaque nuevo, un registro de trazabilidad que el sistema actual no guarda. Esas son las aplicaciones industriales: desarrollos hechos a la medida del proceso.

El punto de partida siempre es el mismo: entender el proceso antes de proponer el equipo. Definimos con el cliente qué tiene que hacer la aplicación, con qué exactitud, a qué ritmo y bajo qué condiciones de planta —humedad, lavado, polvo, temperatura, zona clasificada— y recién entonces se dimensionan la mecánica, la instrumentación y el control. Muchas veces la mejor solución no es un equipo nuevo sino intervenir el que ya existe.

El desarrollo se entrega documentado y con el programa en poder del cliente, sin candados: una aplicación a la medida que solo puede mantener quien la hizo se convierte, con los años, en un problema mayor que el que vino a resolver.',
   '["Sistemas de dosificación y preparación por formulación con control de tolerancia","Aplicaciones de pesaje, conteo y control de llenado en línea","Bancos de prueba y equipos de ensayo para producto propio","Adaptación y repotenciación de máquinas existentes a nuevos formatos o productos","Trazabilidad de lote, registro de variables críticas y generación de reportes","Selección de instrumentación y actuadores según las condiciones reales de planta","Entrega documentada, con programas abiertos y sin candados de fabricante"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/aplicaciones-industriales/tablero-servodrives-apaisada.webp","coverAlt":"Tablero de control abierto con PLC, arrancadores y servoaccionamientos montados sobre la placa de fondo","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/aplicaciones-industriales/tablero-servodrives-apaisada.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/aplicaciones-industriales/tablero-servodrives-apaisada-900.webp","alt":"Tablero de control abierto con PLC, arrancadores y servoaccionamientos montados sobre la placa de fondo","width":1468,"height":826},{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/aplicaciones-industriales/gabinete-terminado-taller.webp","alt":"Gabinete metálico terminado en el taller, con rejillas de ventilación y base de zócalo","width":865,"height":1920}]}'::jsonb, null,
   'Aplicaciones industriales a la medida',
   'Desarrollos industriales a la medida en Cali: dosificación por formulación, pesaje en línea, bancos de prueba, trazabilidad y repotenciación de máquinas.',
   70, true),
  ('refrigeracion-industrial', 'Refrigeración industrial y cuartos fríos', 'Refrigeración industrial', 'refrigeracion',
   'Mantenimiento y control de cuartos fríos y sistemas de refrigeración: sostener la temperatura, registrarla y gastar menos energía haciéndolo.',
   'En un cuarto frío la temperatura no es un número en una pantalla: es el producto. Una desviación sostenida arruina un lote y, en las plantas de alimentos, además deja un hallazgo en la auditoría. Atendemos el mantenimiento y el control de sistemas de refrigeración industrial y cuartos fríos con ese criterio: primero que la temperatura se sostenga, después que se pueda demostrar.

El mantenimiento profesional cubre la parte mecánica y la eléctrica del sistema: revisión de compresores, condensadores y evaporadores, limpieza de intercambiadores, verificación de presiones y temperaturas de operación, control de fugas de refrigerante, estado de válvulas de expansión y ciclos de deshielo, y revisión completa del tablero, protecciones y contactores. Un equipo que arranca mal o deshiela a destiempo consume mucho más de lo que debería y se desgasta antes.

El control es la otra mitad. Instalamos y programamos el sistema de temperatura, alarmas por desviación y registro histórico con marca de tiempo, que es el documento con el que se responde ante una auditoría. Si el cuarto está lejos o desatendido, ese mismo registro se lleva a telemetría y el responsable recibe el aviso apenas la temperatura se sale de rango, no al día siguiente.',
   '["Mantenimiento preventivo y correctivo de cuartos fríos y sistemas de refrigeración","Revisión de compresores, condensadores, evaporadores y válvulas de expansión","Control de fugas, verificación de presiones y temperaturas de operación","Diagnóstico y reparación del tablero eléctrico, protecciones y contactores del equipo","Ajuste de ciclos de deshielo y de la secuencia de arranque para reducir consumo","Control automático de temperatura con alarmas por desviación","Registro histórico fechado de temperatura, útil como soporte ante auditorías","Monitoreo remoto del cuarto frío con aviso al responsable (ver telemetría)"]'::jsonb, '{"cover":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/refrigeracion-industrial/montaje-techo-sala-paneles.webp","coverAlt":"Dos técnicos sobre un andamio instalan equipos en el techo de una sala con paneles aislantes y difusores","gallery":[{"src":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/refrigeracion-industrial/montaje-techo-sala-paneles.webp","srcMovil":"https://bzrjeduxjkwvtdaohjrh.supabase.co/storage/v1/object/public/site-images/servicios/refrigeracion-industrial/montaje-techo-sala-paneles-900.webp","alt":"Dos técnicos sobre un andamio instalan equipos en el techo de una sala con paneles aislantes y difusores","width":1920,"height":1440}]}'::jsonb, null,
   'Refrigeración industrial y cuartos fríos',
   'Mantenimiento de refrigeración industrial y cuartos fríos en Cali: compresores, deshielo, tablero eléctrico, control de temperatura y registro histórico.',
   80, true),
  ('aires-acondicionados', 'Aires acondicionados', 'Aires acondicionados', 'clima',
   'Venta, instalación, reparación y mantenimiento de aire acondicionado, incluidos los equipos que climatizan salas técnicas y tableros.',
   'Atendemos el aire acondicionado de oficinas, áreas de producción y, sobre todo, de los espacios donde la climatización no es comodidad sino condición de operación: salas de servidores, cuartos de control y tableros eléctricos, donde la temperatura y la humedad definen cuánto dura el equipo que hay adentro.

El servicio va de la selección a la operación. Dimensionamos el equipo según la carga térmica real del espacio —área, ocupación, equipos instalados, radiación— y no por metro cuadrado a ojo, porque un equipo sobredimensionado enfría en ciclos cortos, deshumidifica mal y se desgasta igual que uno pequeño trabajando de más. Instalamos el equipo con su acometida eléctrica, sus protecciones, la tubería de refrigerante y el drenaje bien pendientado.

El mantenimiento periódico es lo que sostiene el consumo bajo y la vida útil larga: lavado de serpentines y filtros, verificación de la carga de refrigerante, revisión de drenajes, medición de consumo del compresor y del ventilador, y ajuste de los controles. En diagnóstico y reparación atendemos tanto la falla mecánica como la eléctrica y la de control, que es de donde viene buena parte de las fallas que se atribuyen al equipo.',
   '["Cálculo de carga térmica y selección del equipo según el uso real del espacio","Venta e instalación de aire acondicionado en oficinas y áreas de producción","Climatización de salas de servidores, cuartos de control y tableros eléctricos","Montaje de la acometida eléctrica, protecciones, tubería de refrigerante y drenajes","Mantenimiento preventivo: lavado de serpentines y filtros, carga de refrigerante y drenajes","Diagnóstico y reparación de fallas mecánicas, eléctricas y de control","Revisión de consumo del equipo y ajuste de controles para reducir el gasto de energía"]'::jsonb, '{}'::jsonb, null,
   'Aires acondicionados: venta y mantenimiento',
   'Aire acondicionado en Cali: venta, instalación, reparación y mantenimiento en oficinas, producción, salas de servidores y tableros eléctricos.',
   90, true)
on conflict (slug) do update set
  title            = excluded.title,
  nav_title        = excluded.nav_title,
  icon_key         = excluded.icon_key,
  summary          = excluded.summary,
  description      = excluded.description,
  items            = excluded.items,
  images           = excluded.images,
  meta_title       = excluded.meta_title,
  meta_description = excluded.meta_description,
  sort             = excluded.sort,
  updated_at       = now();
